name: Primer workflow
on: push
jobs:
   hola_mundo:
     runs-on: ubuntu-latest

     steps:
       - name: Instalar pytest
         run: pip install pytest
       - name: Bajar codigo
         uses: actions/checkout@v5
       - name: Probar codigo
         run: pytest test.py
